name: Continious Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # brings source code into dir
      - uses: actions/checkout@v2
      # install node.js
      - uses: actions/setup-node@v1
        with: 
          node-version: 20
      # this is basically a clean install of npm 
      - run: npm ci
      # this test our code
      #- run: npm test
      # make sure code build
      - run: npm run build 
