name: Continious Integration and Continious Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # brings source code into dir
      - uses: actions/checkout@v4
      # install node.js
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      # this is basically a clean install of npm 
      - run: npm ci
      # this test our code
      #- run: npm test
      # make sure code build
      - run: npm run build -- --c "production"
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build -- --c "production"
        env:
          MY_GOOGLE_API_KEY: ${{ secrets.MY_GOOGLE_API_KEY }}
          MY_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COFFEE_REALM }}
          channelId: live
          projectId: coffee-realm