name: Continious Integration and Continious Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # brings source code into dir
      - uses: actions/checkout@v4
      # install node.js
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      # this is basically a clean install of npm 
      - run: npm ci
      # this test our code
      #- run: npm test
      # make sure code build
      - run: npm run build -- --c "production"
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - name: Configure environment variables
        run: |
          echo "export const environment = { production: true, MY_GOOGLE_MAPS_JS_API_KEY: '${{ secrets.MY_GOOGLE_API_KEY }}', firebaseConfig: { FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}', authDomain: 'coffee-realm.firebaseapp.com', projectId: 'coffee-realm', storageBucket: 'coffee-realm.appspot.com', messagingSenderId: '112481585467', appId: '1:112481585467:web:2fdacf93a3653218960f1e', measurementId: 'G-S504NEPG0N' } };" > src/environments/environment.prod.ts

      - name: Build Angular App
        run: npm run build -- --c "production"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COFFEE_REALM }}
          channelId: live
          projectId: coffee-realm